version: '3'

services:
  mysql:
    build: ./db
    container_name: mysql
    restart: always
    ports:
      - '3333:3306'
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend